POST http://localhost:3000/produtos HTTP/1.1
content-type: application/json

{
  "nome": "Mouse Dell",
  "preco": 30
}

###

GET http://localhost:3000/produtos

###

GET http://localhost:3000/produto/4f31c906-87ce-424b-bf16-c096fbd7a4a7

###

PUT http://localhost:3000/produtos/ccc43dd0-613b-4f10-bc06-0a7d1b868dc4
Content-Type: application/json

{
  "nome": "Caneta Lilás",
  "preco": 1.5
}

###

DELETE http://localhost:3000/produto/51de9c31-2729-4a7e-803d-5f78c958f325