POST http://localhost:3000/produtos HTTP/1.1
content-type: application/json

{
  "nome": "Mouse Dell",
  "preco": 30
}

###

GET http://localhost:3000/produtos

###

GET http://localhost:3000/produto/c1cfdd85-39f2-4bc8-9aca-b363ad8bf0db

###

PUT http://localhost:3000/produtos/c1cfdd85-39f2-4bc8-9aca-b363ad8bf0db
Content-Type: application/json

{
  "nome": "Mouse Dell",
  "preco": 1.5
}

###

DELETE http://localhost:3000/produtos/c1cfdd85-39f2-4bc8-9aca-b363ad8bf0db